version: '3.9'

services:
  #MongoDB Services
  mongo_db: 
    container_name: mongo_db_container
    image: mongo:latest
    restart: always
    ports: 
      - 27017:27017
    volumes: 
      - mongo_db:/data/db
    
  #Node API Services
  api: 
    build: .
    ports: 
      - 5000:5000
    volumes: 
      - .:/usr/src/app
    environment:
      APP_PORT: 5000
      DB_URL: mongodb://mongo_db:27017/db-interview
    depends_on: 
      - mongo_db

volumes: 
  mongo_db: {}
  

